[package]
authors = ["Baptiste Gelez <baptiste@gelez.xyz>"]
description = "Rocket fairing for easy internationalization with gettext"
license = "GPL-3.0"
name = "rocket_i18n"
readme = "README.md"
repository = "https://github.com/BaptisteGelez/rocket_i18n"
keywords = ["i18n", "rocket", "gettext", "internationalization", "localization"]
categories = ["internationalization", "localization", "web-programming"]
version = "0.2.0"

[dependencies]
serde_json = "1.0"
tera = "0.11"
gettext = { git = "https://github.com/BaptisteGelez/gettext", rev = "343ce3a33ae52c393cfd8f6f6403eb1dda542186" }
rocket = { git = "https://github.com/SergioBenitez/Rocket", rev = "55459db7732b9a240826a5c120c650f87e3372ce" }

[features]
build = []
